services:
  stable-diffusion-web-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7861:7861"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - "${SD_LOCAL_MODEL_PATH}:/app/models/Stable-diffusion"